ci: add more builds plus caching

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,9 +27,6 @@ jobs:
     docker:
     - image: circleci/buildpack-deps
     shell: /usr/bin/env bash -euo pipefail -c
-    environment:
-    - GOARCH: amd64
-    - GOOS: darwin
     steps:
     - setup_remote_docker
     - checkout
@@ -77,7 +74,139 @@ jobs:
           echo "Unable to restore an builder images, rebuilding from scratch."
         name: Restore static builder image (or best available).
     - run:
-        command: make -f release.Makefile package
+        command: |
+          make -f release.Makefile package
+        environment:
+          EDITION: ''
+          GOARCH: amd64
+          GOOS: darwin
+        name: Compile package
+    - store_artifacts:
+        destination: dest
+        path: dest/
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: static
+        name: Generate static image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: ui-deps
+        name: Generate ui-deps image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: base
+        name: Generate base image cache key.
+    - save_cache:
+        key: package-_darwin_amd64-cache-v1-{{ checksum ".buildcache/static-cache-key" }}
+        paths:
+        - dist/
+  build-darwin-386:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    steps:
+    - setup_remote_docker
+    - checkout
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: static
+        name: Generate static image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: ui-deps
+        name: Generate ui-deps image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: base
+        name: Generate base image cache key.
+    - restore_cache:
+        keys:
+        - static-archive-v1-{{ checksum ".buildcache/static-cache-key" }}
+        - ui-deps-archive-v1-{{ checksum ".buildcache/ui-deps-cache-key" }}
+        - base-archive-v1-{{ checksum ".buildcache/base-cache-key" }}
+    - run:
+        command: |
+          ls -lahR .buildcache
+        name: Info - list files in .buildcache/
+    - run:
+        command: |
+          make -f release.Makefile static-restore || \
+          make -f release.Makefile ui-deps-restore || \
+          make -f release.Makefile base-restore || \
+          echo "Unable to restore an builder images, rebuilding from scratch."
+        name: Restore static builder image (or best available).
+    - run:
+        command: |
+          make -f release.Makefile package
+        environment:
+          EDITION: ''
+          GOARCH: '386'
+          GOOS: darwin
+        name: Compile package
+    - store_artifacts:
+        destination: dest
+        path: dest/
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: static
+        name: Generate static image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: ui-deps
+        name: Generate ui-deps image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: base
+        name: Generate base image cache key.
+    - save_cache:
+        key: package-_darwin_386-cache-v1-{{ checksum ".buildcache/static-cache-key" }}
+        paths:
+        - dist/
   test-ui:
     docker:
     - image: node:10-buster
@@ -299,6 +428,98 @@ jobs:
     - GO_TAGS: null
     - GO_VERSION: 1.12.12
     - GOTESTSUM_VERSION: 0.3.3
+  build-linux-386:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    steps:
+    - setup_remote_docker
+    - checkout
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: static
+        name: Generate static image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: ui-deps
+        name: Generate ui-deps image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: base
+        name: Generate base image cache key.
+    - restore_cache:
+        keys:
+        - static-archive-v1-{{ checksum ".buildcache/static-cache-key" }}
+        - ui-deps-archive-v1-{{ checksum ".buildcache/ui-deps-cache-key" }}
+        - base-archive-v1-{{ checksum ".buildcache/base-cache-key" }}
+    - run:
+        command: |
+          ls -lahR .buildcache
+        name: Info - list files in .buildcache/
+    - run:
+        command: |
+          make -f release.Makefile static-restore || \
+          make -f release.Makefile ui-deps-restore || \
+          make -f release.Makefile base-restore || \
+          echo "Unable to restore an builder images, rebuilding from scratch."
+        name: Restore static builder image (or best available).
+    - run:
+        command: |
+          make -f release.Makefile package
+        environment:
+          EDITION: ''
+          GOARCH: '386'
+          GOOS: linux
+        name: Compile package
+    - store_artifacts:
+        destination: dest
+        path: dest/
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: static
+        name: Generate static image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: ui-deps
+        name: Generate ui-deps image cache key.
+    - run:
+        command: |
+          mkdir -p .buildcache
+          FILE=.buildcache/$NAME-cache-key
+          make -f release.Makefile $NAME-archive-name > $FILE
+          echo "Cache key for layer '$NAME' is $(cat $FILE); written to $FILE"
+        environment:
+          NAME: base
+        name: Generate base image cache key.
+    - save_cache:
+        key: package-_linux_386-cache-v1-{{ checksum ".buildcache/static-cache-key" }}
+        paths:
+        - dist/
   pre-flight-checks:
     docker:
     - image: circleci/buildpack-deps
@@ -447,6 +668,15 @@ workflows:
     jobs:
     - cache-builder-images
     - build-darwin-amd64:
+        requires:
+        - cache-builder-images
+    - build-linux-386:
+        requires:
+        - cache-builder-images
+    - build-darwin-amd64:
+        requires:
+        - cache-builder-images
+    - build-darwin-386:
         requires:
         - cache-builder-images
   ci:
